export default {
  MessageItem: "message-item",
  FromChatbot: "from-chatbot",
  FromMe: "from-me",
  ResponseLoader: "response-loader",
  RichList: "rich-list",
  RichElementImage: "rich-image",
  RichElementPicture: "rich-picture",
  RichElementTitleContainer: "rich-title-container",
  RichElementTitle: "rich-title",
  RichElementSubTitle: "rich-subtitle",
  RichAction: "rich-action",
  EmojiTextMessage: "emoji-text-message",
  PdfFile: "pdf-file-link",
  Nav: "nav",
  NavPrev: "nav-prev",
  NavNext: "nav-next",
  UploadIcon: "upload-icon",
  PluginAreaShow: "plugin-area--show",
  ChatContainerPlugin: "ChatContainer--plugin",
  OfflineComponent: "offline-notice",
}